name: Relase

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    name: Build, Package, Relase, Publish
    runs-on: ubuntu-latest

    steps:
    # Build
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
    - name: packaging
      run: |
        test -e objs/nginx && zip objs/nginx-bin.zip  objs/nginx
    - uses: actions/upload-artifact@v2
      with:
        name: upload-artifact
        path: objs/nginx-bin.zip
        # path: path/**/[abc]rtifac?/*
    # - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag nginx:$(date +%s)

    # Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        # body: |
        #   Changes in this Release
        #   - First Change
        #   - Second Change

    # Publish
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: objs/nginx-bin.zip
        asset_name: nginx-bin-x86_64.zip
        asset_content_type: application/zip
